name: cloudrun-checkov
on:
  pull_request:
    types: [opened]
    
env:
  PR_NUMBER: ${{ github.event.number }}
  GITHUB_TOKEN: ${{secrets.TOKEN}}
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cloudrun-terraform/
      - name: Post comment to GitHub PR
        uses: mshick/add-pr-comment@v1
        if: ${{ failure() && steps.checkov.outcome == 'failure' }}
        with:
         repo-token: ${{ secrets.TOKEN }}
         message: |
            ${{ env.CHECKOV_RESULTS }}          
